# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Hyrla Miranda
email: hyrlammiranda@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Brazilian, Software QA Enginner, IT lover, violinist, chorus contralto, pole fitness, hobbyist model, foods, wine tasting, traveler and dreamer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://hyrlamiranda.github.io" # the base hostname & protocol for your site
twitter_username: hyrlamgeek
github_username:  hyrlamiranda

# Build settings
markdown: kramdown
